spring:
  profiles:
    active: local
jasypt:
  encryptor:
    bean: jasyptStringEncrptor
aws:
  access-key: ENC(wuAWX4jIaTnaAVnU0Xsy/jWWluZWeRAViyIhvweRRiI=)
  secret-key: ENC(TrP3UCBzlyMv9alS0D7KJRB6Sxv/wb/KMEAPFEZg2C1F/mO6eacUtaBCWxito6RARlCrcyK9+9w=)
  region: ap-northeast-2
  bucket-name: watni-resources
---
spring:
  profiles: local
  resources:
    add-mappings: false
  datasource:
    watni:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      maximum-pool-size: 1
      max-lifetime: 55000
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  main:
    allow-bean-definition-overriding: true
logging.level:
  root: DEBUG
---
spring:
  profiles: asciidoc
  resources:
    add-mappings: true
---
spring:
  profiles: schema
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
---
spring:
  profiles: dev
  datasource:
    watni:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://watni.cnt6okgpvlyj.ap-northeast-2.rds.amazonaws.com:3306/watni?useUnicode=true&characterEncoding=utf8
      username: watni_application
      password: ENC(Bp754nRhwnR/wuNXgU0/Lp11G7TakLXRAHKZegzpZGE=)
      maximum-pool-size: 10
      max-lifetime: 55000
    jpa:
      show-sql: true
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    host: ec2-52-78-36-242.ap-northeast-2.compute.amazonaws.com
    port: 6379
    password: ENC(8zxM4iv134exwFlDz84a4A==)
logging.level:
  root: DEBUG